class Stringmethod{
    public static void main(String args[]) {
        String text="Yukesh";
        String text1="Yukesh ";
        String text2="Venkat";
        String text3="yukesh ";
        String name ="     uks      ";
        System.out.println("length of the String");
        System.out.println(text.length());
        System.out.println("");
        System.out.println("Uppercase the String");
        System.out.println(text.toUpperCase());
        System.out.println("");
        System.out.println("Lowercase the String");
        System.out.println(text.toLowerCase());
         System.out.println("");
        System.out.println("IndexOf of the String");
        System.out.println(text.indexOf('e'));
        System.out.println("");
        System.out.println("Two Strings are equal Yukesh=Yukesh");
        System.out.println(text.equals(text1));
        System.out.println("");
        System.out.println("Trim the blank space");
        System.out.println(name.trim());
        System.out.println("");
        System.out.println("compareTo the String Yukesh=Yukesh");
        System.out.println(text.compareTo(text1));
        System.out.println("");
        System.out.println("compareToignorecase the String Yukesh=Yukesh");
        System.out.println(text.compareToIgnoreCase(text3));
        System.out.println("");
        System.out.println("concadinate the two String Yukesh+Venkat");
        System.out.println(text.concat(text2));
        System.out.println("");
        System.out.println("Contain the String u");
        System.out.println(text.contains("u"));
        System.out.println("");
        System.out.println("String Startwith V");
        System.out.println(text2.startsWith("V"));
        System.out.println("");
        System.out.println("String Endswith g");
        System.out.println(text.endsWith("g"));
        System.out.println("");
        System.out.println("Replace the String Yukesh to Uks");
        System.out.println(text.replace("Yukesh", "Uks"));
        System.out.println("");
        System.out.println("String is empty");
        System.out.println(text.isEmpty());
        System.out.println("");
        System.out.println("Replace the first String Yukesh to Mukesh");
        System.out.println(text.replaceFirst("Y", "M"));
        System.out.println("");
        System.out.println("SubString begin");
        System.out.println(text.substring(2));
        System.out.println("");
        System.out.println("SubString begin and end");
        System.out.println(text.substring(2,4));
        System.out.println("");
        System.out.println("Strip same as trim");
        System.out.println(name.strip());
        System.out.println("");
        System.out.println("Repeat the string");
        System.out.println(text1.repeat(5));
    }
}